import json
from pathlib import Path


class PantherProjectBuilder:
    def __init__(self, root="."):
        self.root = Path(root)

    def create_basic_app(self, name: str):
        safe_name = self._safe_name(name)
        project_dir = self.root / safe_name
        project_dir.mkdir(parents=True, exist_ok=True)

        (project_dir / "src").mkdir(exist_ok=True)
        (project_dir / "tests").mkdir(exist_ok=True)

        (project_dir / "README.md").write_text(
            f"# {name}\\n\\nGenerated by Panther Project Builder.\\n"
        )

        (project_dir / "panther.project.json").write_text(
            json.dumps(
                {
                    "name": name,
                    "language": "PantherLang",
                    "version": "0.5",
                    "entry": "src/app.panther",
                },
                indent=2,
            )
            + "\\n"
        )

        app_source = (
            f'app {name} {{\\n'
            '    version "0.5"\\n'
            '}\\n\\n'
            'model Product {\\n'
            '    id: uuid\\n'
            '    title: string required\\n'
            '    price: decimal required\\n'
            '}\\n\\n'
            'page Products {\\n'
            '    title "Products"\\n'
            '    table Product\\n'
            '}\\n'
        )

        (project_dir / "src" / "app.panther").write_text(app_source)
        return project_dir

    def _safe_name(self, name: str) -> str:
        return "".join(ch if ch.isalnum() or ch in ("_", "-") else "_" for ch in name)
