[project]
name = "{{PROJECT_NAME}}"
type = "web"
version = "0.1.0"
language = "panther"

[run]
main = "src/main.panther"


[tooling]
vscode = true
debug = true
tasks = true

[metadata]
created_by = "PantherLang Project Wizard"
template = "web"
