#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


def extract_docs(source: str) -> list[dict]:
    docs: list[dict] = []
    current_comment: list[str] = []
    for line in source.splitlines():
        stripped = line.strip()
        if stripped.startswith("#"):
            current_comment.append(stripped.lstrip("#").strip())
        else:
            if current_comment and stripped:
                tokens = stripped.split()
                kind = tokens[0] if tokens else "stmt"
                name = tokens[1] if len(tokens) > 1 else ""
                if kind in ("fn", "struct", "let", "trait", "enum", "const"):
                    docs.append({
                        "kind": kind,
                        "name": name.rstrip("(").rstrip("{"),
                        "doc": " ".join(current_comment),
                        "line": stripped,
                    })
            current_comment = []
    return docs


def generate_markdown(source_path: Path, docs: list[dict]) -> str:
    lines = [
        f"# PantherLang Documentation — {source_path.name}",
        "",
        f"Auto-generated from `{source_path}`",
        "",
        "## Symbols",
        "",
    ]
    for entry in docs:
        lines.append(f"### {entry['kind']} `{entry['name']}`")
        if entry["doc"]:
            lines.append("")
            lines.append(entry["doc"])
        lines.append("")
        lines.append(f"```panther")
        lines.append(entry["line"])
        lines.append("```")
        lines.append("")
    if not docs:
        lines.append("*No documented symbols found.*")
        lines.append("")
    lines.append("---")
    lines.append("Generated by PantherDoc")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(prog="panther-docgen", description="PantherLang documentation generator")
    parser.add_argument("source", help="Panther source file")
    parser.add_argument("--out", required=True, help="Output markdown file path")
    args = parser.parse_args()

    src = Path(args.source)
    if not src.exists():
        print(f"error: file not found: {src}", file=sys.stderr)
        return 1

    text = src.read_text(encoding="utf-8")
    docs = extract_docs(text)
    markdown = generate_markdown(src, docs)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(markdown, encoding="utf-8")
    print(f"generated:{out} ({len(docs)} symbols)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
