#!/usr/bin/env python3
from pathlib import Path
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("source")
parser.add_argument("--out", required=True)
args = parser.parse_args()

src = Path(args.source)
out = Path(args.out)
out.parent.mkdir(parents=True, exist_ok=True)

text = src.read_text(encoding="utf-8") if src.exists() else ""

lines = [
"# PantherLang Documentation",
"",
f"Source: {src.name}",
"",
"## Preview",
"```panther",
text,
"```",
"",
"Generated by Panther Documentation Generator",
]

out.write_text("\n".join(lines), encoding="utf-8")
print(f"generated:{out}")
