#!/usr/bin/env bash
set -e

echo "🐾 PantherLang Phase 1.15 — Project Builder Bootstrap"
echo "Root: $(pwd)"

mkdir -p language/tools/builder language/tests scripts docs architecture/tools templates/basic_app

cat > architecture/tools/PROJECT_BUILDER.md <<'EOF'
# Panther Project Builder — Phase 1.15

## Purpose
The Project Builder creates standard Panther project structures.

## Phase 1.15 Scope
- Create a basic Panther application folder.
- Generate README.md.
- Generate app.panther.
- Generate panther.project.json.
- Prepare for future `panther new` command.

## Future Scope
- Web templates.
- API templates.
- AI agent templates.
- Panther Studio project creation.
- Panther Cloud deployment manifests.
EOF

cat > language/tools/builder/project_builder.py <<'EOF'
import json
from pathlib import Path


class PantherProjectBuilder:
    def __init__(self, root="."):
        self.root = Path(root)

    def create_basic_app(self, name: str):
        safe_name = self._safe_name(name)
        project_dir = self.root / safe_name
        project_dir.mkdir(parents=True, exist_ok=True)

        (project_dir / "src").mkdir(exist_ok=True)
        (project_dir / "tests").mkdir(exist_ok=True)

        (project_dir / "README.md").write_text(
            f"# {name}\\n\\nGenerated by Panther Project Builder.\\n"
        )

        (project_dir / "panther.project.json").write_text(
            json.dumps(
                {
                    "name": name,
                    "language": "PantherLang",
                    "version": "0.5",
                    "entry": "src/app.panther",
                },
                indent=2,
            )
            + "\\n"
        )

        app_source = (
            f'app {name} {{\\n'
            '    version "0.5"\\n'
            '}\\n\\n'
            'model Product {\\n'
            '    id: uuid\\n'
            '    title: string required\\n'
            '    price: decimal required\\n'
            '}\\n\\n'
            'page Products {\\n'
            '    title "Products"\\n'
            '    table Product\\n'
            '}\\n'
        )

        (project_dir / "src" / "app.panther").write_text(app_source)
        return project_dir

    def _safe_name(self, name: str) -> str:
        return "".join(ch if ch.isalnum() or ch in ("_", "-") else "_" for ch in name)
EOF

cat > language/tools/builder/__init__.py <<'EOF'
from .project_builder import PantherProjectBuilder
EOF

cat > templates/basic_app/README.md <<'EOF'
# Panther Basic App Template

This template is used by Panther Project Builder.
EOF

cat > language/tests/test_phase1_builder.py <<'EOF'
from pathlib import Path
import shutil
from language.tools.builder import PantherProjectBuilder

tmp = Path("tmp_panther_builder_test")
if tmp.exists():
    shutil.rmtree(tmp)
tmp.mkdir()

builder = PantherProjectBuilder(tmp)
project = builder.create_basic_app("PantherDemo")

assert project.exists()
assert (project / "README.md").exists()
assert (project / "panther.project.json").exists()
assert (project / "src" / "app.panther").exists()

content = (project / "src" / "app.panther").read_text()
assert "app PantherDemo" in content
assert "model Product" in content

shutil.rmtree(tmp)

print("✅ Phase 1.15 project builder tests passed.")
EOF

cat > docs/PROJECT_BUILDER.md <<'EOF'
# Panther Project Builder

The Panther Project Builder creates standard Panther project structures.

## Future Command

```bash
panther new PantherStore
```

## Generated Structure

```text
PantherStore/
├── README.md
├── panther.project.json
├── src/
│   └── app.panther
└── tests/
```
EOF

cat > scripts/verify_phase1_builder.sh <<'EOF'
#!/usr/bin/env bash
set -e
cd "$(dirname "$0")/.."
PYTHONPATH="$PWD:$PWD/language" python3 language/tests/test_phase1_builder.py
echo "✅ PantherLang Phase 1.15 project builder verification complete."
EOF

chmod +x scripts/verify_phase1_builder.sh

PYTHONPATH="$PWD:$PWD/language" python3 language/tests/test_phase1_builder.py

echo "--------------------------------"
echo "✅ PantherLang Phase 1.15 Project Builder installed successfully."
echo "Run anytime: bash scripts/verify_phase1_builder.sh"
echo "--------------------------------"
