#!/usr/bin/env bash
set -euo pipefail

echo "============================================================"
echo " PantherLang Phase 9.9 PRO - Release Engineering"
echo "============================================================"

mkdir -p release_engineering releases scripts docs/phase9 examples/phase9_release

cat > release_engineering/release_engine.py <<'PY'
#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import shutil
from datetime import datetime, timezone
from pathlib import Path


class ReleaseError(Exception):
    pass


def project_root() -> Path:
    return Path(__file__).resolve().parents[1]


def create_release(version: str, channel: str = "developer", out_dir: Path | None = None) -> dict:
    root = project_root()
    out_dir = out_dir or (root / "releases" / version)
    out_dir.mkdir(parents=True, exist_ok=True)

    required = [
        "panther",
        "compiler/pipeline/panther_compiler.py",
        "toolchain/production_toolchain.py",
        "toolchain/packager/artifact_packager.py",
        "toolchain/cross_platform/cross_platform_toolchain.py",
    ]

    missing = [item for item in required if not (root / item).exists()]
    if missing:
        raise ReleaseError(f"Missing release requirements: {missing}")

    manifest = {
        "ok": True,
        "phase": "9.9",
        "version": version,
        "channel": channel,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "artifacts": [],
        "required_files": required,
    }

    release_notes = out_dir / "RELEASE_NOTES.md"
    release_notes.write_text(
        f"# PantherLang {version}\n\n"
        f"Channel: {channel}\n\n"
        "Release generated by PantherLang Phase 9.9 Release Engineering.\n",
        encoding="utf-8",
    )

    manifest_path = out_dir / "release.manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True), encoding="utf-8")

    archive = shutil.make_archive(str(out_dir), "gztar", root_dir=out_dir)

    manifest["artifacts"].append(str(archive))
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True), encoding="utf-8")

    return {
        "ok": True,
        "phase": "9.9",
        "version": version,
        "channel": channel,
        "release_dir": str(out_dir),
        "manifest": str(manifest_path),
        "archive": archive,
    }


def main() -> int:
    parser = argparse.ArgumentParser(prog="panther-release")
    sub = parser.add_subparsers(dest="cmd", required=True)

    create = sub.add_parser("create")
    create.add_argument("--version", required=True)
    create.add_argument("--channel", default="developer")
    create.add_argument("--out-dir", default=None)

    args = parser.parse_args()

    try:
        if args.cmd == "create":
            result = create_release(
                args.version,
                channel=args.channel,
                out_dir=Path(args.out_dir) if args.out_dir else None,
            )
            print(json.dumps(result, indent=2, sort_keys=True))
            return 0
    except ReleaseError as exc:
        print(json.dumps({"ok": False, "phase": "9.9", "error": str(exc)}, indent=2))
        return 2

    return 1


if __name__ == "__main__":
    raise SystemExit(main())
PY
chmod +x release_engineering/release_engine.py

cat > examples/phase9_release/release_demo.panther <<'EOF'
print "Phase 9.9 Release Engineering"
EOF

cat > docs/phase9/PHASE_9_9_STATUS.md <<'EOF'
# Phase 9.9 — Release Engineering

Completed:
- Release engine
- Release manifest
- Release notes generation
- Release archive generation
- Panther CLI release bridge
- Release verification script

Next: Phase 9.10 — Final Production Toolchain Integration.
EOF

if ! grep -q 'release_engineering/release_engine.py' panther; then
python3 - <<'PY'
from pathlib import Path
p = Path("panther")
txt = p.read_text()
insert = '  release)\n    shift\n    python3 "$ROOT/release_engineering/release_engine.py" "$@"\n    ;;\n\n'
txt = txt.replace('case "${1:-}" in\n', 'case "${1:-}" in\n' + insert)
p.write_text(txt)
PY
chmod +x panther
fi

cat > scripts/verify_phase9_9_release_engineering.sh <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."

echo "============================================================"
echo " PantherLang Phase 9.9 Release Engineering Verification"
echo "============================================================"

test -f release_engineering/release_engine.py
test -f docs/phase9/PHASE_9_9_STATUS.md
test -f examples/phase9_release/release_demo.panther
echo "✅ structure tests passed"

python3 -m py_compile release_engineering/release_engine.py
echo "✅ python compile passed"

./panther build examples/phase9_release/release_demo.panther --release >/tmp/p99_build.json
grep -q '"ok": true' /tmp/p99_build.json
test -f build/release/release_demo.sh
bash build/release/release_demo.sh | grep -q "Phase 9.9 Release Engineering"
echo "✅ release demo build passed"

rm -rf /tmp/p99_release
./panther release create --version 0.9.9 --channel developer --out-dir /tmp/p99_release >/tmp/p99_release.json
grep -q '"ok": true' /tmp/p99_release.json
grep -q '"phase": "9.9"' /tmp/p99_release.json
test -f /tmp/p99_release/release.manifest.json
test -f /tmp/p99_release/RELEASE_NOTES.md
test -f /tmp/p99_release.tar.gz
grep -q '"version": "0.9.9"' /tmp/p99_release/release.manifest.json
grep -q 'PantherLang 0.9.9' /tmp/p99_release/RELEASE_NOTES.md
echo "✅ release creation tests passed"

tar -tzf /tmp/p99_release.tar.gz | grep -q 'release.manifest.json'
tar -tzf /tmp/p99_release.tar.gz | grep -q 'RELEASE_NOTES.md'
echo "✅ release archive tests passed"

echo "✅ PantherLang Phase 9.9 Release Engineering verification complete."
EOF
chmod +x scripts/verify_phase9_9_release_engineering.sh

echo "[phase9.9] Running verification..."
bash scripts/verify_phase9_9_release_engineering.sh

echo "============================================================"
echo " Phase 9.9 COMPLETE"
echo " Next: Phase 9.10 Final Production Toolchain Integration"
echo "============================================================"
