#!/usr/bin/env bash
set -e

echo "🐾 PantherLang Phase 1.6 — Code Generator Bootstrap"
echo "Root: $(pwd)"

mkdir -p architecture/compiler language/compiler/core language/tests scripts

cat > architecture/compiler/CODE_GENERATOR.md <<'EOF'
# PantherLang Code Generator — Phase 1.6

## Purpose
The Code Generator converts Panther IR into executable target artifacts.

## Phase 1.6 Scope
This is the first target generator. It generates a simple Python runtime module from Panther IR.

## Pipeline
Panther Source → Lexer → Parser → Semantic → IR → Code Generator → Target Code

## Future Targets
- Native Panther VM bytecode
- WebAssembly
- JavaScript/TypeScript
- Python
- Rust
- Go
- Cloud functions
EOF

cat > language/compiler/core/codegen.py <<'EOF'
class PythonCodeGenerator:
    def generate(self, ir_program):
        data = ir_program.to_dict()
        lines = []
        lines.append("# Generated by PantherLang Phase 1.6")
        lines.append(f"APP_NAME = {data['name']!r}")
        lines.append("")
        lines.append("MODELS = {}")
        for model in data.get("models", []):
            fields = [field["name"] for field in model.get("fields", [])]
            lines.append(f"MODELS[{model['name']!r}] = {fields!r}")
        lines.append("")
        lines.append("def describe():")
        lines.append("    return {")
        lines.append("        'app': APP_NAME,")
        lines.append("        'models': MODELS,")
        lines.append("    }")
        lines.append("")
        return "\\n".join(lines)
EOF

cat > language/tests/test_phase1_codegen.py <<'EOF'
from language.models.core_models import PantherModel, PantherField
from language.compiler.core.ir_builder import IRBuilder
from language.compiler.core.codegen import PythonCodeGenerator

product = PantherModel(
    name="Product",
    fields=[
        PantherField("id", "uuid"),
        PantherField("title", "string", required=True),
        PantherField("price", "decimal", required=True),
    ],
)

ir = IRBuilder().build_program_from_models([product], name="PantherStore")
code = PythonCodeGenerator().generate(ir)

assert "APP_NAME" in code
assert "PantherStore" in code
assert "Product" in code
assert "MODELS" in code

print("✅ Phase 1.6 code generator tests passed.")
EOF

cat > scripts/verify_phase1_codegen.sh <<'EOF'
#!/usr/bin/env bash
set -e
cd "$(dirname "$0")/.."
PYTHONPATH="$PWD:$PWD/language" python3 language/tests/test_phase1_codegen.py
echo "✅ PantherLang Phase 1.6 code generator verification complete."
EOF

chmod +x scripts/verify_phase1_codegen.sh

PYTHONPATH="$PWD:$PWD/language" python3 language/tests/test_phase1_codegen.py

echo "--------------------------------"
echo "✅ PantherLang Phase 1.6 Code Generator installed successfully."
echo "Run anytime: bash scripts/verify_phase1_codegen.sh"
echo "--------------------------------"
