#!/usr/bin/env bash
set -euo pipefail

echo "============================================================"
echo " PantherLang Phase 8.5 PRO - Documentation Generator"
echo "============================================================"

mkdir -p tools/docgen docs/generated examples/phase8_docgen scripts tests/phase8_5

cat > tools/docgen/panther_docgen.py <<'PY'
#!/usr/bin/env python3
from pathlib import Path
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("source")
parser.add_argument("--out", required=True)
args = parser.parse_args()

src = Path(args.source)
out = Path(args.out)
out.parent.mkdir(parents=True, exist_ok=True)

text = src.read_text(encoding="utf-8") if src.exists() else ""

lines = [
"# PantherLang Documentation",
"",
f"Source: {src.name}",
"",
"## Preview",
"```panther",
text,
"```",
"",
"Generated by Panther Documentation Generator",
]

out.write_text("\n".join(lines), encoding="utf-8")
print(f"generated:{out}")
PY
chmod +x tools/docgen/panther_docgen.py

cat > examples/phase8_docgen/doc_demo.panther <<'EOF'
module panther.docs

print "Phase 8.5 Documentation Generator"
EOF

cat > scripts/verify_phase8_5_documentation_generator.sh <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."

echo "============================================================"
echo " PantherLang Phase 8.5 Documentation Generator Verification"
echo "============================================================"

test -f tools/docgen/panther_docgen.py
echo "✅ structure tests passed"

python3 tools/docgen/panther_docgen.py \
  examples/phase8_docgen/doc_demo.panther \
  --out docs/generated/doc_demo.md >/dev/null

test -f docs/generated/doc_demo.md
grep -q "PantherLang Documentation" docs/generated/doc_demo.md
grep -q "Phase 8.5 Documentation Generator" docs/generated/doc_demo.md
echo "✅ documentation generation tests passed"

./panther run examples/phase8_docgen/doc_demo.panther | grep -q "Phase 8.5 Documentation Generator"
echo "✅ runtime bridge tests passed"

python3 -m py_compile tools/docgen/panther_docgen.py
echo "✅ python compile passed"

echo "✅ PantherLang Phase 8.5 Documentation Generator verification complete."
EOF
chmod +x scripts/verify_phase8_5_documentation_generator.sh

echo "[phase8.5] Running verification..."
bash scripts/verify_phase8_5_documentation_generator.sh

echo "============================================================"
echo " Phase 8.5 COMPLETE"
echo " Next: Phase 8.6 Formatter"
echo "============================================================"
