class PythonCodeGenerator:
    def generate(self, ir_program):
        data = ir_program.to_dict()
        lines = []
        lines.append("# Generated by PantherLang Phase 1.6")
        lines.append(f"APP_NAME = {data['name']!r}")
        lines.append("")
        lines.append("MODELS = {}")
        for model in data.get("models", []):
            fields = [field["name"] for field in model.get("fields", [])]
            lines.append(f"MODELS[{model['name']!r}] = {fields!r}")
        lines.append("")
        lines.append("def describe():")
        lines.append("    return {")
        lines.append("        'app': APP_NAME,")
        lines.append("        'models': MODELS,")
        lines.append("    }")
        lines.append("")
        return "\\n".join(lines)
