#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import shutil
from datetime import datetime, timezone
from pathlib import Path


class ReleaseError(Exception):
    pass


def project_root() -> Path:
    return Path(__file__).resolve().parents[1]


def create_release(version: str, channel: str = "developer", out_dir: Path | None = None) -> dict:
    root = project_root()
    out_dir = out_dir or (root / "releases" / version)
    out_dir.mkdir(parents=True, exist_ok=True)

    required = [
        "panther",
        "compiler/pipeline/panther_compiler.py",
        "toolchain/production_toolchain.py",
        "toolchain/packager/artifact_packager.py",
        "toolchain/cross_platform/cross_platform_toolchain.py",
    ]

    missing = [item for item in required if not (root / item).exists()]
    if missing:
        raise ReleaseError(f"Missing release requirements: {missing}")

    manifest = {
        "ok": True,
        "phase": "9.9",
        "version": version,
        "channel": channel,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "artifacts": [],
        "required_files": required,
    }

    release_notes = out_dir / "RELEASE_NOTES.md"
    release_notes.write_text(
        f"# PantherLang {version}\n\n"
        f"Channel: {channel}\n\n"
        "Release generated by PantherLang Phase 9.9 Release Engineering.\n",
        encoding="utf-8",
    )

    manifest_path = out_dir / "release.manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True), encoding="utf-8")

    archive = shutil.make_archive(str(out_dir), "gztar", root_dir=out_dir)

    manifest["artifacts"].append(str(archive))
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True), encoding="utf-8")

    return {
        "ok": True,
        "phase": "9.9",
        "version": version,
        "channel": channel,
        "release_dir": str(out_dir),
        "manifest": str(manifest_path),
        "archive": archive,
    }


def main() -> int:
    parser = argparse.ArgumentParser(prog="panther-release")
    sub = parser.add_subparsers(dest="cmd", required=True)

    create = sub.add_parser("create")
    create.add_argument("--version", required=True)
    create.add_argument("--channel", default="developer")
    create.add_argument("--out-dir", default=None)

    args = parser.parse_args()

    try:
        if args.cmd == "create":
            result = create_release(
                args.version,
                channel=args.channel,
                out_dir=Path(args.out_dir) if args.out_dir else None,
            )
            print(json.dumps(result, indent=2, sort_keys=True))
            return 0
    except ReleaseError as exc:
        print(json.dumps({"ok": False, "phase": "9.9", "error": str(exc)}, indent=2))
        return 2

    return 1


if __name__ == "__main__":
    raise SystemExit(main())
