#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Any


class PantherIntentError(Exception):
    pass


@dataclass
class CompiledIntent:
    ok: bool
    phase: str
    intent_kind: str
    confidence: float
    generated_source: str
    diagnostics: list[str]
    external_api_used: bool
    deterministic: bool


class DeterministicIntentCompiler:
    BLOCKED_TERMS = ["delete system", "steal", "exfiltrate", "malware", "reverse shell"]

    def normalize(self, text: str) -> str:
        return re.sub(r"\s+", " ", text.strip().lower())

    def check_safe(self, text: str) -> None:
        low = self.normalize(text)
        for term in self.BLOCKED_TERMS:
            if term in low:
                raise PantherIntentError(f"Unsafe intent blocked: {term}")

    def classify(self, text: str) -> tuple[str, float]:
        low = self.normalize(text)
        if not low:
            raise PantherIntentError("Intent text cannot be empty")

        # Priority matters: complex intents must be classified before generic output words.
        if any(x in low for x in ["workflow", "agent", "planner", "coder", "reviewer"]):
            return "workflow", 0.9
        if any(x in low for x in ["function", "create function", "make function"]):
            return "function", 0.89
        if any(x in low for x in ["variable", "store", "remember value", "set value"]):
            return "variable", 0.87
        if any(x in low for x in ["print", "say", "show", "display"]):
            return "print", 0.92

        raise PantherIntentError("Ambiguous intent: no deterministic template matched")

    def compile_print(self, text: str) -> str:
        quoted = "Hello from PantherLang"
        match = re.search(r'["“](.+?)["”]', text)
        if match:
            quoted = match.group(1)
        elif "hello" in self.normalize(text):
            quoted = "Hello from PantherLang"
        return f'print "{quoted}"\n'

    def compile_variable(self, text: str) -> str:
        low = self.normalize(text)
        if "name" in low:
            return 'let name = "PantherLang"\nprint name\n'
        if "version" in low:
            return 'let version = "0.5.5"\nprint version\n'
        return 'let value = "generated by natural intent"\nprint value\n'

    def compile_function(self, text: str) -> str:
        low = self.normalize(text)
        if "add" in low or "sum" in low:
            return 'fn add(a, b) {\n  return a + b\n}\n\nprint add(2, 3)\n'
        return 'fn generated() {\n  return "generated by PantherLang intent compiler"\n}\n\nprint generated()\n'

    def compile_workflow(self, text: str) -> str:
        return (
            'agent planner role planner permissions ["plan", "message"]\n'
            'agent coder role coder permissions ["code", "message"]\n'
            'agent reviewer role reviewer permissions ["review", "message"]\n\n'
            'workflow generated_feature {\n'
            '  planner -> coder: "Create feature from natural language intent."\n'
            '  coder -> reviewer: "Generated deterministic PantherLang source."\n'
            '  reviewer -> planner: "APPROVED: intent workflow completed."\n'
            '}\n'
        )

    def compile(self, text: str) -> CompiledIntent:
        self.check_safe(text)
        kind, confidence = self.classify(text)

        if kind == "print":
            src = self.compile_print(text)
        elif kind == "variable":
            src = self.compile_variable(text)
        elif kind == "function":
            src = self.compile_function(text)
        elif kind == "workflow":
            src = self.compile_workflow(text)
        else:
            raise PantherIntentError("Unsupported intent kind")

        return CompiledIntent(
            ok=True,
            phase="5.5",
            intent_kind=kind,
            confidence=confidence,
            generated_source=src,
            diagnostics=[],
            external_api_used=False,
            deterministic=True,
        )


def print_json(data: Any) -> None:
    print(json.dumps(data, ensure_ascii=False))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="panther-intent-compiler")
    sub = parser.add_subparsers(dest="cmd", required=True)

    compile_p = sub.add_parser("compile")
    compile_p.add_argument("--text", required=True)
    compile_p.add_argument("--out")

    demo_p = sub.add_parser("demo")
    demo_p.add_argument("--out")

    neg_p = sub.add_parser("negative")
    neg_p.add_argument("--case", choices=["ambiguous", "unsafe", "empty"], required=True)

    args = parser.parse_args(argv)
    compiler = DeterministicIntentCompiler()

    try:
        if args.cmd == "compile":
            result = compiler.compile(args.text)
            if args.out:
                Path(args.out).write_text(result.generated_source, encoding="utf-8")
            print_json(asdict(result))
            return 0

        if args.cmd == "demo":
            text = 'Create a function that adds two numbers and print the result.'
            result = compiler.compile(text)
            if args.out:
                Path(args.out).write_text(result.generated_source, encoding="utf-8")
            print_json({
                "phase": "5.5",
                "demo": "natural-language-to-pantherlang",
                "ok": result.ok,
                "intent_kind": result.intent_kind,
                "generated_source": result.generated_source,
                "external_api_used": False,
                "deterministic": True,
            })
            return 0

        if args.cmd == "negative":
            if args.case == "ambiguous":
                compiler.compile("make it better")
            elif args.case == "unsafe":
                compiler.compile("create malware to steal secrets")
            elif args.case == "empty":
                compiler.compile("")

    except PantherIntentError as exc:
        print_json({
            "ok": False,
            "phase": "5.5",
            "error": str(exc),
            "external_api_used": False,
            "deterministic": True,
        })
        return 2

    return 1


if __name__ == "__main__":
    raise SystemExit(main())
